import { Router } from "express";
import { AccountRoutes } from "../module/account/account.route.js";
import { AccountTransferRoutes } from "../module/accountTransfer/accountTransfer.route.js";
import { AttendanceRoutes } from "../module/attendance/attendance.route.js";
import { AuthRoutes } from "../module/auth/auth.route.js";
import { BusinessSettingsRoutes } from "../module/businessSettings/businessSettings.route.js";
import { CustomerRoutes } from "../module/customer/customer.route.js";
import { CustomerPaymentRoutes } from "../module/customerPayment/customerPayment.route.js";
import { EmployeeRoutes } from "../module/employee/employee.route.js";
import { ExpenseRoutes } from "../module/expense/expense.route.js";
import { ExpenseCategoryRoutes } from "../module/expenseCategory/expenseCategory.route.js";
import { InventoryRoutes } from "../module/inventory/inventory.route.js";
import { InvestmentRoutes } from "../module/investment/investment.route.js";
import { LoanRoutes } from "../module/loan/loan.route.js";
import { LoanLenderRoutes } from "../module/loanLender/loanLender.route.js";
import { MonthlyTargetRoutes } from "../module/monthlyTarget/monthlyTarget.route.js";
import { OtherIncomeRoutes } from "../module/otherIncome/otherIncome.route.js";
import { ProductRoutes } from "../module/product/product.route.js";
import { ProfitWithdrawalRoutes } from "../module/profitWithdrawal/profitWithdrawal.route.js";
import { PurchaseRoutes } from "../module/purchase/purchase.route.js";
import { RecycleBinRoutes } from "../module/recycleBin/recycleBin.route.js";
import { SaleRoutes } from "../module/sale/sale.route.js";
import { SalePaymentRoutes } from "../module/salePayment/salePayment.route.js";
import { SalaryTransactionRoutes } from "../module/salaryTransaction/salaryTransaction.route.js";
import { ShareholderRoutes } from "../module/shareholder/shareholder.route.js";
import { SubscriptionRoutes } from "../module/subscription/subscription.route.js";
import { SuperAdminRoutes } from "../module/superAdmin/superAdmin.route.js";
import { SupplierRoutes } from "../module/supplier/supplier.route.js";
import { SupplierPaymentRoutes } from "../module/supplierPayment/supplierPayment.route.js";
import { UploadRoutes } from "../module/upload/upload.route.js";
import { UserRoutes } from "../module/user/user.route.js";

const router = Router();

router.use("/auth", AuthRoutes);
router.use("/users", UserRoutes);
router.use("/subscriptions", SubscriptionRoutes);
router.use("/super-admin", SuperAdminRoutes);
router.use("/business-settings", BusinessSettingsRoutes);
router.use("/shareholders", ShareholderRoutes);
router.use("/accounts", AccountRoutes);
router.use("/account-transfers", AccountTransferRoutes);
router.use("/monthly-targets", MonthlyTargetRoutes);
router.use("/expense-categories", ExpenseCategoryRoutes);
router.use("/suppliers", SupplierRoutes);
router.use("/customers", CustomerRoutes);
router.use("/products", ProductRoutes);
router.use("/investments", InvestmentRoutes);
router.use("/profit-withdrawals", ProfitWithdrawalRoutes);
router.use("/loan-lenders", LoanLenderRoutes);
router.use("/loans", LoanRoutes);
router.use("/expenses", ExpenseRoutes);
router.use("/other-incomes", OtherIncomeRoutes);
router.use("/purchases", PurchaseRoutes);
router.use("/supplier-payments", SupplierPaymentRoutes);
router.use("/inventory", InventoryRoutes);
router.use("/sales", SaleRoutes);
router.use("/sale-payments", SalePaymentRoutes);
router.use("/customer-payments", CustomerPaymentRoutes);
router.use("/employees", EmployeeRoutes);
router.use("/salary-transactions", SalaryTransactionRoutes);
router.use("/attendance", AttendanceRoutes);
router.use("/recycle-bin", RecycleBinRoutes);
router.use("/uploads", UploadRoutes);

export const indexRoute = router;
